language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mrinal2196/complex_client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrinal2196/mrinal2196/complex_client_test:latest npm run test

after_success:
  - docker build -t mrinal2196/multi-client ./client
  - docker build -t mrinal2196/multi-nginx ./nginx
  - docker build -t mrinal2196/multi-server ./server
  - docker build -t mrinal2196/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mrinal2196/multi-client
  - docker push mrinal2196/multi-nginx
  - docker push mrinal2196/multi-server
  - docker push mrinal2196/multi-worker